### ISSUE TITLE
Bug in the preview code - mark up buttons showing incorrect text

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#146]
The mark up button <gap> </gap> is coming up as illegible on the preview tab, see screenshots
<img width="950" alt="Screenshot 2023-03-07 at 9 01 37 am" src="https://user-images.githubusercontent.com/91518014/223611416-fc31a8ca-b732-4a53-8184-a0401fa94fd3.png">
<img width="903" alt="Screenshot 2023-03-07 at 9 01 29 am" src="https://user-images.githubusercontent.com/91518014/223611427-610b61ba-639f-4a02-ad8e-1d37f401d41c.png">

**Comment by marcolarosa** [comment]
The `<gap>` element on line 6 seems to be causing an issue?

**Comment by sophlew** [comment]
That gap elements isn't working either - see the preview screenshot, no gap

**Comment by sophlew** [comment]
Looks like two issues 1: Line mark up isn't leaving a line space.
2. gap mark up is showing as illegible 
I've tested it on another manuscript, screenshots attached 
<img width="1236" alt="Screenshot 2023-03-09 at 10 12 50 am" src="https://user-images.githubusercontent.com/91518014/223873783-0c127f92-4e3a-4e7b-a6de-28d00484af3f.png">
<img width="1240" alt="Screenshot 2023-03-09 at 10 12 45 am" src="https://user-images.githubusercontent.com/91518014/223873792-cdc11109-661e-4cf5-be95-ea84db3aa631.png">
<img width="1234" alt="Screenshot 2023-03-09 at 10 12 03 am" src="https://user-images.githubusercontent.com/91518014/223873793-b40d32fc-bf44-46fe-a99d-855520dec385.png">
<img width="1209" alt="Screenshot 2023-03-09 at 10 11 57 am" src="https://user-images.githubusercontent.com/91518014/223873795-5042b3b6-f720-4e30-b539-0d409b9c6305.png">

**Comment by Conal-Tuohy** [comment]
I think I must have chosen to render the `<gap>` elements as "[illegible]" in the HTML preview panel because illegibility is usually the reason why a transcriber would skip over some text and not transcribe it (NB that's what the `gap` element means; [a section of the source text omitted from the transcription](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-gap.html)). Should I change that rendering so that it says `[not transcribed]` or similar?

As for the other issue, where a `<line>` element isn't being rendered as a blank line in the HTML preview, it looks to me like that's happening only where the `<line>` element is empty. I will look into it.

**Comment by Conal-Tuohy** [comment]
It turns out that the `tei-to-html.xsl` stylesheet doesn't include a template specifically for `line` elements so they're handled by a generic template which transforms them into  `div` elements. That works fine for `line` elements that contain text, but if a `line` element is empty, it yields an empty `div` element:

```html
<div class="tei-line"/>
```

... which will not produce any visible output in a browser (an empty `div` element is meaningless, actually).

I should probably just add a template for handling `line` elements specifically and render them using HTML `br` (line break) elements.

**Comment by marcolarosa** [comment]
@marcolarosa remove `gap` control from TEI editor in UI

@Conal-Tuohy `line` to be visible

**Comment by marcolarosa** [comment]
@gap removed

**Comment by Conal-Tuohy** [comment]
@sophlew can you verify and close this issue if it's all good? thanks

**Comment by sophlew** [comment]
unclear and line markup are both working
