### ISSUE TITLE
Unable to log in using Google auth

### ISSUE THREAD

**Issue by Conal-Tuohy** [CoEDL/nyingarn-workspace#149]
When I click the button to log in through Google, I end up back at the same page.

http://localhost:9000/login

The JS console in my browser shows a failed POST to POSThttp://localhost:9000/api/auth/google/code which returns an HTTP 401 (unauthorized) response code.

The log at the back end shows:

```
api_1             | 2023-03-15 01:50:25.861+0000 - info - POST /auth/google/code - incoming request
db_1              | 2023-03-15 01:50:26.957 UTC [42] ERROR:  column "identifier" does not exist at character 50
db_1              | 2023-03-15 01:50:26.957 UTC [42] STATEMENT:  SELECT "id", "email", "givenName", "familyName", "identifier", "provider", "locked", "upload", "administrator", "data", "createdAt", "updatedAt" FROM "users" AS "user" WHERE "user"."email" = 'conal.tuohy@gmail.com';
api_1             | 2023-03-15 01:50:26.959+0000 - info - Unauthorized
api_1             | 2023-03-15 01:50:26.960+0000 - info - request completed
```

I'm almost certain I've dealt with this before but I can't recall the details

**Comment by marcolarosa** [comment]
I've just tested and I can get in via google so the code is ok. Looks to me like you have a very old version of the DB without the identifier column in the users table. The fix is to docker exec into the DB container, connect to the db (psql nyingarn), drop the user table and then save any API file which will trigger a service restart that will then recreate that table.

**Comment by Conal-Tuohy** [comment]
I had to drop the entire nyingarn database (DROP DATABASE nyingarn), and when that wasn't enough to get the DB reinitialized, I deleted the `/postgresql/data` directory, which was enough to get the DB re-initialized.
