### ISSUE TITLE
Collection Metadata

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#153]
Questions from Bridey: 

- [ ] Will the collection metadata fields be updated to mirror item level metadata? E.g. collection metadata doesn’t include the ‘recorded at’ field in original source information. The collection metadata also has the old descriptions for Content Language vs Subject Language.

- [ ] Does the collection metadata filter down to associated items? E.g. if I add a ‘date created’ in the collection, will its items show this too.

- [ ] Would it be possible for me to have a look at someone else’s collection on Nyingarn if anyone has created one, to get a sense of how they’re using the metadata?

- [ ] Is there a way to see a user view of collections/items at this stage?
- [ ] Sophie to set up a group collection metadata meeting

**Comment by marcolarosa** [comment]
> Questions from Bridey:
> 
>     * [ ]  Will the collection metadata fields be updated to mirror item level metadata? E.g. collection metadata doesn’t include the ‘recorded at’ field in original source information. The collection metadata also has the old descriptions for Content Language vs Subject Language.

Collection metadata may be different to item metadata. That's the point of the having another meeting solely about collection metadata in order to determine what we want described. The version that is in place now is a copy of an earlier version of the item metadata; hence the discrepancies.

> 
>     * [ ]  Does the collection metadata filter down to associated items? E.g. if I add a ‘date created’ in the collection, will its items show this too.

No. Collection metadata is totally separate to item metadata. Implementing this capability would be extraordinarily difficult and would likely have unintended consequences; ie item metadata getting overwritten by something coming from the collection.

> 
>     * [ ]  Would it be possible for me to have a look at someone else’s collection on Nyingarn if anyone has created one, to get a sense of how they’re using the metadata?

In the repo yes. In the workspace no.

> 
>     * [ ]  Is there a way to see a user view of collections/items at this stage?

No. That's in the repo.

> 
>     * [ ]  Sophie to set up a group collection metadata meeting

Yes
