### ISSUE TITLE
Question: How should users markup a particular language? 

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#172]
Example from Amy here, DumontDurville_1834-381.
How should the French language be marked up? Screen shot shows the current error message
![Screenshot 2023-05-01 at 12 26 12 pm](https://user-images.githubusercontent.com/91518014/235393359-cfe6e775-c104-43b9-b6a2-9512397e7f87.png)

**Comment by Conal-Tuohy** [comment]
For tagging the language of the text contained in a particular element, users should add the `xml:lang` attribute to that element , like so:

```xml
<line xml:lang="fr">VOCABULAIRE</line>
```
Here, the `xml:lang` attribute is attached to a `line` element, but it can go on any element, and applies to all the text contained in that element.

The `language` element shouldn't appear in the transcription at all; it's only for use inside the `teiHeader`, within a `langUsage` element which lists the languages appearing in the transcription. There, the `ident` attribute identifies the language itself, and the `xml:lang` attribute would identity the language in which the language is named  e.g. here's the French language with the English name "French":
```xml
<language ident="fr" xml:lang="en">French</language>
```
or, the Spanish name for the French language:
```xml
<language ident="fr" xml:lang="es">francés</language>
```

There is also a `lang` element which _can_ be used inside the transcription, to tag the names of languages (in the same way that e.g. `persName` can tag the name of a person mentioned in the text), e.g. 
```xml
<lang>French</lang>
```

**Comment by Conal-Tuohy** [comment]
Generally, the main language of a TEI text would be tagged (with an `xml:lang` attribute) on the `text` element of the document. In the Nyingarn workspace no-one gets to see the `body` element because they're transcribing within `surface` elements which each represent just one page. But the workspace does allow someone to mark the main language of a document in a metadata-entry form, I think, and this _should_ end up as `xml:lang` attributes when the entire TEI file is reconstituted. I am pretty sure it doesn't do this currently, though.

- [ ] Check that a document's main language is converted to a `text/@xml:id` when a TEI document is exported

**Comment by nthieberger** [comment]
I've been doing this for the Italian in New Norcia 38

<line><term xml:lang="it">Carne </term>- pálgò <term xml:lang="en">flesh,
meat</term></line>

Ultimately it would be good to have the language word encoded too.

**Comment by Conal-Tuohy** [comment]
I think if the text as a whole is tagged with the indigenous language, then tagging all the Italian words as exceptions will mean the whole text is tagged correctly.
