### ISSUE TITLE
trouble importing DigiVol content with different naming structures

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#19]
Trying to import DigiVol csv files BM1684A for Buller Murphy .. was various numbering after BM1684A. For example 
BM1648A101-0024.jpg
BM1648A101-0005.jpg
BM1684A911-0001.jpg
BM1648A101-0006.jpg
BM1648A102-0001.jpg
BM1648A101-0001.jpg
BM1684A911-0002.jpg
BM1684A910-0004.jpg
BM1648A101-0004.jpg
BM1648A102-0002.jpg
BM1648A101-0007.jpg
BM1648A101-0009.jpg
BM1648A104-0004.jpg

Multiple parts of the larger Buller Murphy manuscripts were transcribed together in DigiVol. workspace isn't breaking down/recognising the files within. Is there another way? apart from entering each item BM1648A101 or BM1648A911 individually?

**Comment by marcolarosa** [comment]
Those names don't match the naming scheme. According to the current rules you need to create individual items: BM1648A101, BM1684A911 etc and then upload just the files for that item.

**Comment by sophlew** [comment]
Can they be brought back together afterwards? Or linked in the repository as all Buller Murphy manuscript pages

**Comment by marcolarosa** [comment]
No. Not at this stage. Until now each of those items is a standalone thing.

**Comment by sophlew** [comment]
So what are the options moving forward? Would I do one part BM1648A72 for example? then clone the metadata so I could add the next folder parts BM1648A73, BM1648A81 etc.

**Comment by nthieberger** [comment]
This is something for the repository to capture, relationships between
items. But the workspace will just treat each separately.

**Comment by marcolarosa** [comment]
I think this needs some more thought.

Modelling parts of a single manuscript as separate items doesn't make sense unless the items align with sections of the manuscript in some sensible way (e.g. chapter boundaries or something). But if we do this we now need some top level construct that we can link these items to - like a manuscript item that has no images but contains links to the items that form part of it (this would be like a paradisec collection). Otherwise, the repo will just see them as individual items.

And until now we have said an item is a manuscript - ie each item is standalone.

@sophlew in answer to your question, yes, you would clone (template in the describo world) the metadata of the first item then apply it to each of the others and adjust the differences.

**Comment by sophlew** [comment]
It is easier to do larger DigiVol expeditions too, with multiple pages and folders but I think I can work around this by renaming the csv file each time for import

**Comment by sophlew** [comment]
The system of reusing the same Digivol csv file but named differently has worked for examples BM1684A911 and BM1684A910. workspace collected right files based on the item name

**Comment by marcolarosa** [comment]
The answer to this is not the creation of a collection to map the items together though we may need that in the future (e.g. a Bates collection that relates all of the bates manuscripts).

The solution is here to rework the item / resource names. The item is BM1648A and the resources are 1010024, 1010005 etc:

BM1648A-1010024.jpg
BM1648A-1010005.jpg

**Comment by sophlew** [comment]
Following this conversation, I've done a test: a single item BM1648A in workspace with many resources Versus multiple items (BM1648A101, BM1648A104,  BM1648A72, BM1648A91). 
<img width="548" alt="Screen Shot 2022-03-08 at 10 43 37 am" src="https://user-images.githubusercontent.com/91518014/157137129-483f9edf-a024-4a72-a0b1-e61f52efa809.png">
I'll chat with Amy but the first option looks more promising. Getting the naming right before entry into DigiVol helps but isn't terribly hard to change.

**Comment by marcolarosa** [comment]
Closing this ticket as I think we've resolved the issue. At the very least, we can now relate items via collections.
