### ISSUE TITLE
Deleting permissions documents bug

### ISSUE THREAD

**Issue by brideylea** [CoEDL/nyingarn-workspace#231]
Once permissions forms have been uploaded in the 'publish' tab, they cannot be removed in the 'administration' tab. I'm experiencing this issue in ANRossDefinitions9798. When pressing the red delete button, the document disappears for a second and then reappears. I have noted this issue with items published to the repository, but this time it is happening with an unpublished item. 

https://github.com/CoEDL/nyingarn-workspace/assets/152234516/6d737e42-0251-4395-b95c-f40ba71fdfdd

**Comment by r-tae** [comment]
For `ANRossDefinitions9798` specifically this is because the permission forms were named `.pdf.PDF` The code that fetches the forms finds them anyway because it doesn't care about a double extension. (it just looks for `-rights-holder-permission\.pdf` anywhere in the filename)

The delete button, however, doesn't ever see the real name of the file, it just tries to delete a file called exactly `ANRossDefinitions9798-language-authority-permission.pdf`, which fails silently.

**Comment by r-tae** [comment]
I don't know why they had the double extension though, but there's no capitalised `.PDF` anywhere in the codebase so I assume it happened when you renamed the FCM pdf (if your file extensions are hidden in the file explorer it is easy to do without realising it)

**Comment by brideylea** [comment]
Aha! Amazing, thanks River. Good to know and thank you for fixing. I'm sure the double extension was my fault so no issues there.
