### ISSUE TITLE
Uploading mutiple tei.xml doucments under one item

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#51]
Creating a new ticket for this
![Screenshot (171)](https://user-images.githubusercontent.com/91518014/170614574-19a71741-e476-41db-8625-56256ba4385c.png)
Bates 34 has multiple folders with 100 plus page transcriptions see screenshot. I would prefer to prepare each folder of Bates34 containing 1 docx document at a time but this means there will be multiple Bates34-tei.xml documents. Does that make sense? How do we get around this?

**Comment by marcolarosa** [comment]
So based on our chat it should take the next document and extract data for any items that it doesn't yet have. If it fails because of a duplicate item then we need to rework the ingestion to be more permissive; ie don't extract the data for existing items but don't fail as an error either.

Something to consider is whether we need to actually keep these files once we're done. At the moment we are but in this instance we would only end up with the document ingested last so what does it mean keeping that and none of the previous ones? And if we don't keep these documents does it matter? The data is in so these imported documents aren't really needed anymore.

**Comment by sophlew** [comment]
Test item Bates 34, the workspace has accepted multiple documents named Bates34-tei.xml with different data.  
Re keeping and accessing files, at the moment the user can only download individual transcription files per manuscript page (see screenshot) not the whole manuscript
![Screenshot (208)](https://user-images.githubusercontent.com/91518014/172281832-5d3344be-04c5-4a46-93e7-ef8d42b5bb15.png)

**Comment by marcolarosa** [comment]
This works as intended.
