### ISSUE TITLE
Excessive TEI markup still coming out

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#73]
Test case: [Issue - excessive tei markup / Bates 34](https://drive.google.com/drive/folders/1BYMSFXPsFRxGwxSspJzctV1zKvUwfipY?usp=sharing)

**Comment by marcolarosa** [comment]
A new release of the workspace has just been pushed with the code from the `test-revision` branch and which also contains the fixes for excessive tei markup. Processing the Bates34 tei file from the google drive shows that not all of the markup is being stripped out yet. See screenshots following:

<img width="641" alt="Screen Shot 2022-07-25 at 2 32 42 pm" src="https://user-images.githubusercontent.com/2639995/180699763-6a4f7cdc-7c85-4223-a5da-2de4e31d89fa.png">

<img width="632" alt="Screen Shot 2022-07-25 at 2 36 25 pm" src="https://user-images.githubusercontent.com/2639995/180699769-d4ac9041-59cf-43b5-ac87-e290967e46c1.png">

Specifically, all the `text-align` markup should be removed.

**Comment by Conal-Tuohy** [comment]
I discussed this with @sophlew and my memory of that discussion was that we want to retain `text:align:right` and `text-align:center` but continue to drop `text-align:left`, and also add `text-align:justify` to the list of values we can drop.

The reasoning is that the "right" and "center" values are likely to actually be meaningful, and will produce a useful effect when we come to render the TEI in a "preview" panel. They also don't occur very often so don't add much clutter. Whereas the "left" values are pure cruft (it's just Word's default text-alignment), and I think the "justify" values are also just another document-wide default for the text-encoding agency that produced this particular file.

So I think `text-align:justify` is the only thing to remove.

**Comment by sophlew** [comment]
Thanks, Marco & Conal. This is a good place to stop and clarify with @nthieberger 
I personally think the remaining TEI markup: Text:align in all versions - right, center, left and justify are messy and confusing for everyday viewers but are there research implications? 
@nthieberger should these be removed too?

**Comment by nthieberger** [comment]
Probably a good idea to keep "center " as it can identify headings that are otherwise stripped of any formatting. I'm not surethat "right" serves a function so it can go. But we can review these decisions if it ibecomes clear we are getting rid of useful information.

**Comment by sophlew** [comment]
Thanks Nick. 
@Conal-Tuohy Please remove everything but the text-align:center

**Comment by marcolarosa** [comment]
@nthieberger You can't assume that something in the middle of the page is a heading. If it can be identified as a heading then it should be marked up in tei as a heading. Otherwise, keeping the center marking can't really be used.

**Comment by nthieberger** [comment]
Thanks for that. Needs some analysis of docs, but if they come from MS Word
it is likely they were put there as headings.

**Comment by Conal-Tuohy** [comment]
We've discussed the text-align markup a few times, and agreed on keeping `right` and `center`. I'm not sure if there's some new reason to reopen the question? I'd be happy to cut out `rend` where we can, but I think there's some useful information encoded in that alignment which we should keep in some form.

My analysis of the MSWord texts I've seen is that the `text-align:right` paragraphs are page numbers. They are in the case listed above. So generally you'll have no more than one per page, at the top. I don't think there's much harm in retaining it, myself, even in a purely presentational form, as a `rend` attribute value, because they occur rarely enough not to add significant clutter, and it at least allows for a "preview" panel to present it in a way that a person is more likely to understand as a page number. But probably a better solution would be for the MSWord ingestion stylesheet to guess at the semantics for it: if it's numeric and appears at the top of the page, and is aligned right, then change it to a [`fw` (forme work) element](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-fw.html), e.g. `<fw>365/34/1</fw>`. That's less cluttered than `rend="text-align:right"`, and does capture the meaning. If it doesn't match those rules, we could keep it as is (just as a `p` with a `rend`), but I expect there'd be hardly any that wouldn't look like a page number.

Similarly a paragraph with `text-align:center` is generally going to be a heading, and I'd say that should be converted to a `<head>` if it appears as the start of a section, or a `<label>` element otherwise. 

> Labels may also be used to represent a [label](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-label.html) or heading attached to a paragraph or sequence of paragraphs not treated as a structural division, or to a group of verse lines.
https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-label.html

```<p rend="text-align:center">Animal Names</p>``` ⇒ ```<label>Animal Names</label>```

That's better than simply discarding this information, I think, and is really no more difficult to do.

The CSS used in the "preview" panel can assume right- and center-alignment for these elements, so we wouldn't need to retain `rend` attributes in the TEI.

**Comment by sophlew** [comment]
Last we spoke the decision was made to strip all excessive mark up such as Font, style, Text-align:right and text-align:justify and at that point, as discussed I wanted to check in with Nick. I also felt this was a better place to see an almost clean verbatim transcription to further discuss:
1. Colour coding for Tei-markup and transcription text and 2. user view options. 
@Conal-Tuohy Thanks for these suggestions. The centre text is usually a title of a few words, in capitals or underlined so I don't think we lose any additional information. The numbers are a secondary page numbering system explaining the collection/folder or folio and page. I don't think it needs anything unless it is very simple

**Comment by marcolarosa** [comment]
* [ ] remove text-align:justify

Keep all of the other text aligns (right and center, left already removed).

All other markup already being removed.

* [ ] mark up centered text as headings - err on the side of false positive
* [ ] mark up right aligned numbers as page numbers - err on the side of false positive
