### ISSUE TITLE
Lorem-ipsum-digivol.sh not working with Bates35 example in drive

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#75]
### 1 Describe the problem

The example [Succeeds - Digivol upload/Bastes35](https://drive.google.com/drive/folders/1mfmye4F4FkEzntu-rlwLOexvRgp_4zW1?usp=sharing) was copied to the test-data folder (Succeeds-digivol-upload/Bates35) and the script `./lorem-ipsum-digivol.sh` was run over it as:

```
`./lorem-ipsum-digivol.sh` ../test-data/Succeeds-digivol-upload/Bates35/Bates35-digivol.csv`
```

The script created a file `Bates35-digivol.csv.new.csv` but the content was not changed.

This example has `not` been committed to the repo as it can't be anonymised. To test, you will need to get the original file from drive.

**Comment by Conal-Tuohy** [comment]
This input file seems a bit different. In other digivol files I've seen, all the fields were quoted, but in this one they aren't. I wonder what the story is there? Perhaps the file has been edited in Excel or similar? Does that sound plausible, @sophlew ?

Anyway ... there seems to be a parsing problem which I will get onto debugging

**Comment by marcolarosa** [comment]
Please leave this until further notice.

**Comment by marcolarosa** [comment]
[Issue - digivol upload failure / Bates35 - github 75](https://drive.google.com/drive/folders/1mfmye4F4FkEzntu-rlwLOexvRgp_4zW1?usp=sharing)

**Comment by Conal-Tuohy** [comment]
- Fixed the CSV parser to handle unquoted cells in CSV in 8d3fbb322d0eaf05b6f761e5b2b47b39a4e74fae (actually it later turned out that DigiVol always quotes cells, but this file had just been resaved in Excel which only quotes cells which actually contain commas).
- Generated and committed the obfuscated version of the test data file in 836e07392c8924c802d23d0feea71c0fbe1e5e48
