### ISSUE TITLE
Nice error reporting when digivol file input can't be read

### ISSUE THREAD

**Issue by marcolarosa** [CoEDL/nyingarn-workspace#90]
Since digivol encoding can be an issue let's make the parser report a nice error. If digivol import can't be read say something like: ```Can't read file. Is the encoding correct? It must be Unicode (UTF-8) - {need link to website support page}". ```

Relates to https://github.com/CoEDL/nyingarn-workspace/issues/59

**Comment by Conal-Tuohy** [comment]
Note: the XPath error which the stylesheet will throw in the case of an encoding error will be either:

-  https://www.w3.org/TR/xpath-functions-31/#ERRFOUT1190 if the parser thinks it knows what encoding the file should be, but is unable to parse it because the file is borked, or because the parser doesn't support that encoding, or
-  https://www.w3.org/TR/xpath-functions-31/#ERRFOUT1200 if the parser can't work out what encoding the file uses, but knows it's not UTF-8

From the user's perspective there's no practical difference between these two errors, I think. It might be worth catching either error in the XSLT layer and throwing a single "Bad encoding" error instead.
